import { SectionInput } from "./validations/sections";

export const defaultSection: SectionInput[] = [
  {
    type: "about",
    order: 0,
    content: {
      title: "About us",
      description:
        "We’re a growing team building modern solutions to real problems. Our mission is to create products that are simple, reliable, and genuinely useful. We believe in teamwork, ownership, and delivering meaningful impact every day.",
    },
  },
  {
    type: "job",
    order: 1,
  },
];

export const jobsData = [
  {
    title: "Full Stack Engineer",
    work_policy: "Remote",
    location: "Berlin, Germany",
    department: "Product",
    employment_type: "Full time",
    experience_level: "Senior",
    job_type: "Temporary",
    salary_range: "AED 8K–12K / month",
    job_slug: "full-stack-engineer-berlin",
  },
  {
    title: "Business Analyst",
    work_policy: "Hybrid",
    location: "Riyadh, Saudi Arabia",
    department: "Customer Success",
    employment_type: "Part time",
    experience_level: "Mid-level",
    job_type: "Permanent",
    salary_range: "USD 4K–6K / month",
    job_slug: "business-analyst-riyadh",
  },
  {
    title: "Software Engineer",
    work_policy: "Remote",
    location: "Berlin, Germany",
    department: "Sales",
    employment_type: "Contract",
    experience_level: "Senior",
    job_type: "Permanent",
    salary_range: "SAR 10K–18K / month",
    job_slug: "software-engineer-berlin",
  },
  {
    title: "Marketing Manager",
    work_policy: "Hybrid",
    location: "Boston, United States",
    department: "Engineering",
    employment_type: "Part time",
    experience_level: "Mid-level",
    job_type: "Temporary",
    salary_range: "AED 8K–12K / month",
    job_slug: "marketing-manager-boston",
  },
  {
    title: "UX Researcher",
    work_policy: "Hybrid",
    location: "Boston, United States",
    department: "Engineering",
    employment_type: "Full time",
    experience_level: "Senior",
    job_type: "Permanent",
    salary_range: "USD 4K–6K / month",
    job_slug: "ux-researcher-boston",
  },
  {
    title: "AI Product Manager",
    work_policy: "On-site",
    location: "Athens, Greece",
    department: "Operations",
    employment_type: "Full time",
    experience_level: "Junior",
    job_type: "Internship",
    salary_range: "INR 8L–15L / year",
    job_slug: "ai-product-manager-athens",
  },
  {
    title: "Sales Development Representative",
    work_policy: "Remote",
    location: "Berlin, Germany",
    department: "Marketing",
    employment_type: "Full time",
    experience_level: "Mid-level",
    job_type: "Temporary",
    salary_range: "INR 8L–15L / year",
    job_slug: "sales-development-representative-berlin",
  },
  {
    title: "Frontend Engineer",
    work_policy: "Hybrid",
    location: "Athens, Greece",
    department: "Engineering",
    employment_type: "Part time",
    experience_level: "Junior",
    job_type: "Temporary",
    salary_range: "USD 80K–120K / year",
    job_slug: "frontend-engineer-athens",
  },
  {
    title: "Sales Development Representative",
    work_policy: "On-site",
    location: "Cairo, Egypt",
    department: "Sales",
    employment_type: "Contract",
    experience_level: "Senior",
    job_type: "Internship",
    salary_range: "USD 4K–6K / month",
    job_slug: "sales-development-representative-cairo",
  },
] as const;
